# ============================================================================
# Configuration for System Resource Monitoring Agent
# ============================================================================

# API Configuration
api:
  endpoint: "http://localhost:8000/api/metrics"
  timeout: 10  # seconds
  
# Data Collection Settings
collection:
  interval_seconds: 300  # 5 minutes (300 seconds)
  include_processes: true
  process_limit: 10  # Top N processes to track
  
  # Enable/disable specific metric categories
  collect_cpu: true
  collect_memory: true
  collect_gpu: true
  collect_disk: true
  collect_network: true
  collect_processes: true

# System Information
system:
  location: "Computer Lab A"  # Update with actual lab location
  department: "Computer Science"  # Update with department name
  
# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "agent.log"
  max_log_size_mb: 10
  backup_count: 5

# Database Configuration (alternative to API - direct DB connection)
# Uncomment and configure if you want direct database connection instead of API
# database:
#   host: "localhost"
#   port: 5432
#   database: "lab_resource_monitor"
#   user: "data_collector"
#   password: "your_password_here"
#   sslmode: "prefer"

# Advanced Settings
advanced:
  retry_on_failure: true
  max_retries: 3
  retry_delay_seconds: 60
  
  # Buffer metrics locally if API is unavailable
  enable_local_buffer: true
  buffer_max_size: 1000  # Maximum number of metric entries to buffer
  buffer_file: "metrics_buffer.json"

# Alerting (optional - client-side pre-checks)
alerts:
  enabled: false
  thresholds:
    cpu_percent: 95
    ram_percent: 90
    disk_percent: 85
    gpu_temp: 85
